### ISSUE TITLE
admins.ini file overwritten on container restart when $COUCHDB_ADMIN_PASSWORD given

### ISSUE THREAD

**Issue by jest** [rocoto/docker-couchdb#1]
Whenever the existing container starts, the entrypoint code overwrites `etc/admins.ini` file if `COUCHDB_ADMIN_PASSWORD` environment variable is set. If it happens that before restart you added some admins, e.g. with Futon, they are gone now.

I suggest adding additional check and only create `etc/admins.ini` when it does not exist:

``` bash
  if [ -n "$COUCHDB_ADMIN_PASSWORD" -a ! -f /data/etc/local.ini ]; then
```

**Comment by lupomontero** [comment]
@jest: Thanks for the feedback ;-) Well spotted!

I've pushed some changes that should address this. When upgrading to the latest image (already available on docker hub) make sure you append the contents of `/data/etc/admins.ini` to `/data/etc/local.ini` before starting the new container. Now all "local" config including admins is stored in `local.ini` for more consistency.

Can you check the latest image to see if this issue is now fixed?

**Comment by jest** [comment]
Looks good, thanks!
